name: lost_souls
description: A web app that uses Dart.
# version: 1.0.0
# homepage: https://www.example.com
# author: Bopzor <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:

dev_dependencies:
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
